"""Add penalty_fee to Offer

Revision ID: 89034b1dbfb5
Revises: 28d51f697de2
Create Date: 2023-04-16 16:23:47.306695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89034b1dbfb5'
down_revision = '28d51f697de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penalty_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('negotiation', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_column('negotiation')
        batch_op.drop_column('penalty_fee')

    # ### end Alembic commands ###
